# schema/codegen/generation.toml
# Code generation settings

[output]
base_dir = "src/generated"
module_file = "mod.zig"

[files]
help = "help.zig"
parser = "parser.zig"
structs = "structs.zig"
types = "types.zig"
validation = "validation.zig"

[features]
cli_completions = true
documentation = true
examples = true
json_schema = true
tests = true

[optimization]
inline_small_functions = true
compile_time_validation = true
zero_cost_abstractions = true
