# schema/structs/settings.toml
# Global settings structure

[struct]
name = "Settings"
description = "Global default settings that apply to all tasks"

[fields.env_file]
type = "${common.types.boolean}"
required = false
description = "Automatically load environment variables from .env file"
default = false

[fields.env_file_path]
type = "${common.types.optional_string}"
description = "Custom path to environment file"
default = "${common.defaults.env_file_default}"
required = false

[fields.working_directory]
aliases = ["work_dir"]
default = "."
description = "Default working directory for all tasks"
pattern = "${common.patterns.not_empty_string}"
required = false
type = "${common.types.string}"

[fields.shell]
aliases = ["sh"]
default = "$SHELL"
description = "Shell to use for command execution"
examples = ["/bin/bash", "/bin/zsh", "/opt/homebrew/bin/fish", "C:\\Windows\\System32\\cmd.exe"]
pattern = "${common.patterns.not_empty_string}"
required = false
type = "${common.types.string}"

[fields.environment_variables]
aliases = ["env_vars"]
description = "Default environment variables for all tasks"
key_pattern = "${common.patterns.constant_convention}"
required = false
type = "${common.types.optional_string_map}"
value_pattern = "${common.patterns.not_empty_string}"

[fields.variables]
aliases = ["vars"]
description = "Default template variables for command substitution"
key_pattern = "${common.patterns.naming_convention}"
required = false
type = "${common.types.optional_string_map}"
value_pattern = "${common.patterns.not_empty_string}"
