# schema/structs/task.toml
# Task structure definition

[struct]
name = "Task"
description = "Individual task definition with command and configuration"
generate_init = true
generate_deinit = true

[fields.command]
type = "${common.types.string}"
description = "Shell command to execute for this task"
required = true
min_length = 1
max_length = "${common.constraints.max_command_length}"
pattern = "${common.patterns.command_pattern}"
examples = ["echo 'Hello World'", "npm run build", "python script.py"]

[fields.description]
type = "${common.types.optional_string}"
description = "Human-readable description of what this task does"
max_length = "${common.constraints.max_description_length}"

[fields.confirm]
type = "${common.types.boolean}"
description = "Require user confirmation before executing this task"
default = "${common.defaults.confirm_false}"

[fields.timeout]
type = "${common.types.optional_integer}"
description = "Maximum execution time in seconds"
min_value = "${common.constraints.min_timeout}"
max_value = "${common.constraints.max_timeout}"

[fields.retry_count]
type = "${common.types.integer}"
description = "Number of times to retry task on failure"
default = "${common.defaults.retry_count_zero}"
max_value = "${common.constraints.max_retry_count}"

[fields.dependencies]
type = "${common.types.string_array}"
description = "List of task names that must complete successfully before this task runs"
item_pattern = "${common.patterns.task_name}"
max_items = "${common.constraints.max_dependencies}"

[fields.work_dir]
type = "${common.types.optional_string}"
description = "Override default working directory for this task"
pattern = "${common.patterns.file_path}"

[fields.shell]
type = "${common.types.optional_string}"
description = "Override default shell for this task"
pattern = "${common.patterns.shell_path}"

[fields.environment]
type = "${common.types.optional_string_map}"
description = "Task-specific environment variables"
key_pattern = "${common.patterns.env_var_name}"
max_entries = "${common.constraints.max_environment_vars}"

[fields.variables]
type = "${common.types.optional_string_map}"
description = "Task-specific template variables for command substitution"
key_pattern = "${common.patterns.variable_name}"
max_entries = "${common.constraints.max_variables}"

[fields.watch]
type = "${common.types.string_array}"
description = "File patterns to monitor for automatic task re-execution"
max_items = "${common.constraints.max_watch_patterns}"

[fields.parallel]
type = "${common.types.boolean}"
description = "Allow this task to run in parallel with other parallel tasks"
default = "${common.defaults.parallel_true}"
