# schema/common/defaults.toml
# Default values used across schemas

[defaults]
shell = "/bin/bash"
work_dir = "."
env_file = ".env"

[defaults.platforms]
linux = { shell = "/bin/bash", line_ending = "\\n" }
macos = { shell = "/bin/zsh", line_ending = "\\n" }
windows = { shell = "cmd", line_ending = "\\r\\n" }
