# schema/common/types.toml
# Reusable type definitions

[types]
string = "string"
optional_string = "?string"
boolean = "bool"
optional_boolean = "?bool"
integer = "u32"
optional_integer = "?u32"
string_array = "[]string"
optional_string_array = "?[]string"
string_map = "HashMap(string)"
optional_string_map = "?HashMap(string)"

# Composite types
settings_type = "Settings"
task_type = "Task"
config_type = "Config"
task_map = "HashMap(Task)"
