# schema/common/types.toml
# Reusable type definitions

[types]
string = "string"
optional_string = "?string"
boolean = "bool"
optional_boolean = "?bool"
integer = "u32"
optional_integer = "?u32"
string_array = "[]string"
optional_string_array = "?[]string"
string_map = "HashMap(string)"
optional_string_map = "?HashMap(string)"

[types.composite]
config = "config"
global = "global"
task = "task"
task_map = "HashMap(Task)"
